@echo on
choco install firefox -y
choco install razer-synapse-2 -y
choco install 7zip -y
choco install phpstorm -y
choco install docker-desktop -y
choco install git -y
choco install nodejs.install -y
choco install malwarebytes -y
choco install skype -y
choco install ccleaner -y
choco install python3 -y
choco install paint.net -y
choco install keepass.install -y
choco install spotify -y
choco install everything -y
choco install mysql.workbench -y
choco install defraggler -y
choco install sharex -y
choco install discord -y
choco install setdefaultbrowser v
choco install nircmd -y
choco install multimonitortool -y
choco install steam -y
choco install f.lux -y 
choco install phpstorm -y
choco install sourcetree -y
choco install setdefaultbrowser -y
choco install nvidia-inspector -y
choco install jbs -y
choco install disable-nvidia-telemetry -y
pause